/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_gpuUtility */

#ifndef _Included_src_gpuUtility
#define _Included_src_gpuUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_gpuUtility
 * Method:    caSimNoRank
 * Signature: ([[I[[Ljava/lang/String;[[Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_src_gpuUtility_caSimNoRank
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     src_gpuUtility
 * Method:    caSimRank
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICAL Java_src_gpuUtility_caSimRank
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     src_gpuUtility
 * Method:    raSimProc
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_src_gpuUtility_raSimProc
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
