all:
	gcc -fPIC -shared -I/c -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers src_gpuUtility.c -o ../lib/libgpuUtility.jnilib
