/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_gpuUtility */

#ifndef _Included_src_gpuUtility
#define _Included_src_gpuUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_gpuUtility
 * Method:    caSimNoRank
 * Signature: ([[I[[Ljava/lang/String;[[Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_src_gpuUtility_caSimNoRank
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     src_gpuUtility
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_gpuUtility_getString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     src_gpuUtility
 * Method:    getArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_src_gpuUtility_getArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
